# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/OkuhiraShunri/Documents/verilog/DDP/vivado/sim2/DDP_sim2.srcs/sources_1/ip/PS/PS.xci
# IP: The module: 'PS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OkuhiraShunri/Documents/verilog/DDP/vivado/sim2/DDP_sim2.gen/sources_1/ip/PS/PS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/OkuhiraShunri/Documents/verilog/DDP/vivado/sim2/DDP_sim2.srcs/sources_1/ip/PS/PS.xci
# IP: The module: 'PS' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/OkuhiraShunri/Documents/verilog/DDP/vivado/sim2/DDP_sim2.gen/sources_1/ip/PS/PS_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PS'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
